inherit:
    - base.yaml

model:
    n_positions: 1001
    n_cluster: 2
    n_dims: 6


training:
    task: cluster_nd # TODO
    data: cluster_nd # TODO
    n_cluster: 2
    save_sample: True
    curriculum:
        points: #点的个数
            start: 200 # TODO
            end: 200 # TODO
            inc: 0 # TODO
            interval: 20000 # TODO
        dims: # 点的纬度
            start: 6
            end: 6
            inc: 0
            interval: 2000
    learning_rate: 0.0001 
    # resume_id: 24c1872a-7ff7-427f-9d41-ff57d6b7ee1f # TODO


out_dir: ../numerical-in-context-learning/result/model/cluster_nd2  # TODO

wandb:
    name: "cluster_ndtest"
    notes: cluster_ndtest